#' @include DBDriver.R
NULL

#' An S4 class to represent a SQL Server connection
#'
#' This class extends the \code{\link[RJDBC:JDBCConnection-class]{JDBCConnection}}
#' class to represent a SQL Server connection.
#'
#' @slot jc Java object representing the connection.
#' @slot identifier.quote quote character for a SQL Server identifier can be a
#' single quotation mark (\code{\'}), a left or right bracket (\code{[]}), or a
#' double quotation mark (\code{\"}). Usually inherited from
#' \code{\linkS4class{SQLServerDriver}}.
#' @references
#' \href{http://msdn.microsoft.com/en-us/library/ms175874.aspx}{SQL Server identifiers}
#' @export

setClass("SQLServerConnection", contains = 'JDBCConnection')

#' Connect to/disconnect from a SQL Server database.
#'
#' @param drv An objected generated by \code{\link{SQLServer}}, or an existing
#' \code{\linkS4class{SQLServerConnection}}. If a connection, the connection
#' will be cloned.
#' @param server The address of the server to connect to.
#' @param port The port to connect to on \code{server}. The default \code{NULL}
#' which maps to \code{1433} in the MS JDBC Driver API. You do not have to
#' precede the port with a \code{:}.
#' @param instance The instance to connect to on \code{server}. If not specified,
#' a connection to the default instance is made.
#' @param ... One or more \href{http://msdn.microsoft.com/en-us/library/ms378988(v=sql.110).aspx}{optional connection properties.}.
#' Note if you intend to set the integratedSecurity property to \code{'true'}
#' from the default API value of \code{'false'}, you will need to make a specific
#' authentication driver available to the Java Virtual Machine. See
#' \code{\link{RSQLServer}}
#' @return a \code{linkS4Class{SQLServerConnection}} object
#' @examples
#' \dontrun{
#' dbConnect(SQLServer(), ServerName, 1437, user = 'username', integratedSecurity = 'true')
#' }
#' @references
#' \href{http://msdn.microsoft.com/en-us/library/ms378428(v=sql.110).aspx}{Building the Connection URL}
#' \href{http://msdn.microsoft.com/en-us/library/ms378988(v=sql.110).aspx}{Setting the Connection Properties}
#' @export

setMethod(f = 'dbConnect', signature = "SQLServerDriver",
  definition = function (drv, server, port = NULL, instance = NULL, ...)
  {
    dots <- list(...)
    properties <- rJava::.jnew('java/util/Properties')
    for (property in names(dots))
    {
      rJava::.jcall(properties, "Ljava/lang/Object;", "setProperty", property,
        dots[[property]])
    }
    url <- build_ss_connection_url(server, port, instance)
    jc <- rJava::.jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", url,
      properties)
    new("SQLServerConnection", jc = jc, identifier.quote = drv@identifier.quote)
  }
)

# # setMethod("dbSendQuery",
# #   signature(conn = "SQLServerConnection", statement = "character"),
# #   def = function (conn, statement, ..., list=NULL)
# #   {
# #     statement <- as.character(statement)[1L]
# #     ## if the statement starts with {call or {?= call then we use
# #     ## CallableStatement
# #     if (isTRUE(as.logical(grepl("^\\{(call|\\?= *call)", statement))))
# #     {
# #       s <- .jcall(conn@jc, "Ljava/sql/CallableStatement;", "prepareCall",
# #         statement, check=FALSE)
# #       .verify.JDBC.result(s, "Unable to execute JDBC callable statement ",
# #         statement)
# #       if (length(list(...)))
# #         .fillStatementParameters(s, list(...))
# #       if (!is.null(list))
# #         .fillStatementParameters(s, list)
# #       r <- .jcall(s, "Ljava/sql/ResultSet;", "executeQuery", check=FALSE)
# #       .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",
# #         statement)
# #     } else if (length(list(...)) || length(list))
# #     {
# #       ## use prepared statements if there are additional arguments
# #       s <- .jcall(conn@jc, "Ljava/sql/PreparedStatement;", "prepareStatement",
# #         statement, check=FALSE)
# #       .verify.JDBC.result(s, "Unable to execute JDBC prepared statement ",
# #         statement)
# #       if (length(list(...)))
# #         .fillStatementParameters(s, list(...))
# #       if (!is.null(list))
# #         .fillStatementParameters(s, list)
# #       r <- .jcall(s, "Ljava/sql/ResultSet;", "executeQuery", check=FALSE)
# #       .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",
# #         statement)
# #     } else
# #     {
# #       ## otherwise use a simple statement some DBs fail with the above)
# #       s <- .jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")
# #       .verify.JDBC.result(s, "Unable to create simple JDBC statement ",
# #         statement)
# #       r <- .jcall(s, "Ljava/sql/ResultSet;", "executeQuery",
# #         as.character(statement)[1], check=FALSE)
# #       .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",
# #         statement)
# #     }
# #     md <- .jcall(r, "Ljava/sql/ResultSetMetaData;", "getMetaData", check=FALSE)
# #     .verify.JDBC.result(md, "Unable to retrieve JDBC result set meta data for ",
# #       statement, " in dbSendQuery")
# #     new("SQLServerResult", jr=r, md=md, stat=s, pull=.jnull())
# #   }
# # )
# #
# # setMethod("dbExistsTable", "SQLServerConnection",
# #   def=function (conn, name, ...)
# #   {
# #     s <- .jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")
# #     .verify.JDBC.result(s, "Unable to create simple JDBC statement ", statement)
# #     r <- .jcall(s, "Ljava/sql/ResultSet;", "executeQuery",
# #       paste0("SELECT TOP 0 * FROM ", name), check=FALSE)
# #     .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", statement)
# #     TRUE
# #   }
# # )
# #
